#!/usr/bin/env python3
"""
Analyze L2 cache hit rates from rocprof counter collection CSV output.

This script reads a CSV file generated by rocprofv3 and calculates the average
L2 hit rate for the persistent_gemm_all_scatter_wg_specialization kernel.
"""

import csv
import sys
from pathlib import Path
from typing import List, Tuple


def parse_csv(csv_path: Path, kernel_name: str) -> List[Tuple[float, float]]:
    """
    Parse CSV file and extract TCC_HIT_sum and TCC_MISS_sum pairs for the specified kernel.
    
    Args:
        csv_path: Path to the CSV file
        kernel_name: Name of the kernel to analyze
        
    Returns:
        List of (hit_count, miss_count) tuples, one per kernel invocation
    """
    hit_miss_pairs = []
    
    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        
        # Group rows by Correlation_Id to pair hits and misses
        correlation_data = {}
        
        for row in reader:
            if row['Kernel_Name'] == kernel_name:
                corr_id = row['Correlation_Id']
                counter_name = row['Counter_Name']
                counter_value = float(row['Counter_Value'])
                
                if corr_id not in correlation_data:
                    correlation_data[corr_id] = {}
                
                correlation_data[corr_id][counter_name] = counter_value
        
        # Extract hit/miss pairs
        for corr_id, counters in sorted(correlation_data.items()):
            if 'TCC_HIT_sum' in counters and 'TCC_MISS_sum' in counters:
                hit_miss_pairs.append((counters['TCC_HIT_sum'], counters['TCC_MISS_sum']))
    
    return hit_miss_pairs


def calculate_hit_rate(hits: float, misses: float) -> float:
    """
    Calculate L2 cache hit rate.
    
    Args:
        hits: Number of L2 cache hits
        misses: Number of L2 cache misses
        
    Returns:
        Hit rate as a percentage (0-100)
    """
    total = hits + misses
    if total == 0:
        return 0.0
    return (hits / total) * 100.0


def main():
    if len(sys.argv) < 2:
        script_dir = Path(__file__).parent
        csv_path = script_dir / "profile_counter_collection.csv"
    else:
        csv_path = Path(sys.argv[1])
    
    if not csv_path.exists():
        print(f"Error: CSV file not found: {csv_path}", file=sys.stderr)
        sys.exit(1)
    
    kernel_name = "persistent_gemm_all_scatter_wg_specialization"
    
    print(f"Analyzing L2 hit rates for kernel: {kernel_name}")
    print(f"Reading from: {csv_path}\n")
    
    # Parse the CSV
    hit_miss_pairs = parse_csv(csv_path, kernel_name)
    
    if not hit_miss_pairs:
        print(f"No data found for kernel: {kernel_name}", file=sys.stderr)
        sys.exit(1)
    
    print(f"Found {len(hit_miss_pairs)} kernel invocations\n")
    
    # Calculate hit rates for each invocation
    hit_rates = []
    for i, (hits, misses) in enumerate(hit_miss_pairs):
        hit_rate = calculate_hit_rate(hits, misses)
        hit_rates.append(hit_rate)
        print(f"Invocation {i+1:3d}: Hits={hits:12.0f}, Misses={misses:12.0f}, Hit Rate={hit_rate:6.2f}%")
    
    # Calculate and print average
    avg_hit_rate = sum(hit_rates) / len(hit_rates)
    print(f"\n{'='*70}")
    print(f"Average L2 Hit Rate: {avg_hit_rate:.2f}%")
    print(f"{'='*70}")


if __name__ == "__main__":
    main()
